# Generated by Django 2.1.5 on 2019-01-22 21:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accepted', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'dispatch',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverId', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipmentId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('driver_accepted', models.ForeignKey(db_column='driver', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Driver')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.AddField(
            model_name='dispatch',
            name='driver',
            field=models.ForeignKey(db_column='dispatch_driver', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Driver'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='shipment',
            field=models.ForeignKey(db_column='dispatch_shipment', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Shipment'),
        ),
    ]
