# Generated by Django 2.1.5 on 2019-01-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190125_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipmentId',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
